config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts, only: [:index, :new, :create] do
    resources :meows, only: [:create, :destroy]
  end
end

app/models/meow.rb
class Meow < ActiveRecord::Base
  belongs_to :user,
  inverse_of: :meows

  belongs_to :post,
  inverse_of: :meows

  validates :user, presence: true
  validates :post, presence: true
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user,
  inverse_of: :posts

  has_many :meows,
  dependent: :destroy,
  inverse_of: :post

  validates :user, presence: true
  validates :image, presence: true
  validates :description, length: { maximum: 140 }

  def self.by_recency
    order(created_at: :desc)
  end

  def has_meow_from?(user)
    meow_from(user).present?
  end

  def meow_from(user)
    meows.find_by(user_id: user.id)
  end

  mount_uploader :image, PostImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts,
  dependent: :destroy,
  inverse_of: :user

  has_many :meows,
  dependent: :destroy,
  inverse_of: :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meows_controller.rb
class MeowsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    # Build a Meow by the current user for the post
    meow = current_user.meows.build(post: post)

    respond_to do |format|
      if meow.save
        format.html { redirect_to :back, notice: "We heard your Meow!" }
        format.json { render json: meow }
      else
        format.html { redirect_to :back }
        format.json { render json: meow.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.meows.destroy(params[:id])

    respond_to do |format|
      # Respond the same way we were before if the request format is html
      format.html do
        flash[:notice] = "All evidence of your meowing has been destroyed!"
        redirect_to :back
      end

      # Respond with a "204 No Content" to signify that the request has been
      # fulfilled
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  def index
    @posts = Post.all.by_recency
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path, notice: "Post created successfully."
    else
      flash.now[:notice] = "There were some errors with your Post."
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :description)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catstagram</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Sign in", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Meow</h1>

<% @posts.each do |post| %>
<!-- A wrapper element for each Post that also has the value of the Post's id -->
<div data-post-id="<%= post.id %>">
  <%= image_tag post.image.url %>

  <p><div id='meow-count'><%= pluralize post.meows.count, "Meow" %></div></p>

  <% if user_signed_in? %>
    <% if post.has_meow_from?(current_user) %>
      <%= button_to "Remove Meow", post_meow_path(post, post.meow_from(current_user)),
      method: :delete,
      form: { data: { 'meow-button' => 'delete' } } %>
    <% else %>
      <%= button_to "Meow", post_meows_path(post),
      method: :post,
      form: { data: { 'meow-button' => 'create' } } %>
    <% end %>
  <% end %>

  <p><%= post.description %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>